---
- name: Presentation remove
  hosts: lgu
  become: false
  
  tasks:
    - name: Remove pres
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /home/devops/Ansible_course_2.0.zip
        - /home/devops/Ansible_course_2.0
    - name: rm
      shell: rm tomcat*
      args:
        chdir: /home/devops
