---
- name: Ansible Course prepare playbook
  hosts: lgu
  become: yes

  roles:
    - { role: common_ansible, when: "ansible_os_family == 'Debian'" }
    - { role: ansible, when: "ansible_os_family == 'Debian'" }
