---
- name: Git-Jenkins-Sonar Course prepare playbook
  hosts: knopa 
  become: no
  
  vars:
    boxes:
      BbJeNeS:
        box_name: BbJeNeS
        file: BbJeNeS_v0.6.box
        md5: 1ba53bff731cd36adae09f292996a3a0 # v0.6
        url:
        src: "/mnt" # directory
        dest: "D:\\DevOps\\gjs_course" # directory
        ip: 192.168.33.104
        mem: 6144

  pre_tasks:
    - debug:
        var: ansible_distribution
        verbosity: 1
    - fail:
      when: "{{ ansible_distribution | match(\"Windows 10\") }}"
    - name: Change standby timeout
      win_command: POWERCFG -change -standby-timeout-ac 1440 

  roles:
    - { role: virtualbox_win }
    - { role: vagrant_win }
