---
- name: Install Ansible Python modules
  shell: "pip install {{ item }}"
  with_items:
    - paramiko
    - PyYAML
    - Jinja2
    - pycrypto
- name: Check if vagrant_{{ vagrant_vers }} is installed
  shell: "vagrant -v | grep {{ vagrant_vers }}"
  register: vagrant_check_deb
- name: Install Vagrant                                                    
  apt:                                                                     
    deb: "https://releases.hashicorp.com/vagrant/{{ vagrant_vers }}/vagrant_{{ vagrant_vers }}_x86_64.deb"
    update_cache: yes
  when: vagrant_check_deb.rc == 1 
- name: Install VitrualBox                                                 
  apt:
    name: "{{ item }}"                                                     
    state: latest
  with_items:
    - virtualbox                                                           
    - virtualbox-dkms
    - cpu-checker
- name: Ensure all folders are in place
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ course_user }}"
    group: "{{ course_user }}"
  with_items:
    - "/opt/prepare/boxes"
    - "/opt/boxes"
    - "/opt/boxes/master"
    - "/opt/boxes/nix_slave"
    - "/opt/boxes/win_slave"
    - "{{ course_path }}/vms/shared"
