---
- name: Install Tomcat
  hosts: nix
  become: true
  
  vars:
    app: httpd
    tomcat_v: 7.0.79
    tomcat_port: 9090
    admin_user: admin
    admin_pass: admin123
  
  #environment:
  #  JAVA_HOME: /etc/alternatives/jre_1.8.0

  tasks:
    - name: Stop Apache Web Server
      service:
        name: "{{ app }}"
        state: stopped
    - name: remove user
      user:
        name: petya
        state: absent
    - name: remove group
      group:
        name: httpd_admin
        state: absent
    - name: Istall Java
      yum: 
        name: java
        state: latest
    - name: Add Tomcat group
      group:
        name: tomcat
        state: present
    - name: Add Tomcat user
      user:
        name: tomcat
        groups: tomcat
        state: present
    - name: Create folder
      file:
        path: /opt/tomcat
        state: directory
        owner: tomcat
        group: tomcat
        mode: 0755
    - name: Install Tomcat
      unarchive:
        src: "/opt/soft/nix/apache-tomcat-{{ tomcat_v }}.tar.gz"
        dest: /opt/tomcat/
    - name: Correct permissions
      file:
        path: "/opt/tomcat/apache-tomcat-{{ tomcat_v }}"
        owner: tomcat
        group: tomcat
        recurse: yes
    - name: Configure Tomcat
      lineinfile:
        path: "/opt/tomcat/apache-tomcat-{{ tomcat_v }}/conf/server.xml"
        regexp: '<Connector port="8080" '
        line: '<Connector port="{{ tomcat_port }}" protocol="HTTP/1.1"'
        state: present
        backrefs: yes
      notify:
        - restart tomcat
    - name: Configure Tomcat User
      blockinfile:
        path: "/opt/tomcat/apache-tomcat-{{ tomcat_v }}/conf/tomcat-users.xml"
        block: |
          <role rolename="manager-gui"/>
          <user username="{{ admin_user }}" password="{{ admin_pass }}" roles="manager-gui"/>
        insertafter: "<tomcat-users>"
    - name: Register Tomcat as Service
      template:
        src: tomcat_service.j2
        dest: /etc/systemd/system/tomcat.service
    - name: Start and Enable Tomcat service
      service:
        name: tomcat
        enabled: yes
        state: started
    - name: Check Tomcat running
      service:
        name: tomcat
      register: tomcat_out
      failed_when: not 'running' in tomcat_out.status.SubState
    - name: Deploy test app
      copy:
        src: /opt/soft/nix/ansible-demo-app.war
        dest: "/opt/tomcat/apache-tomcat-{{ tomcat_v }}/webapps/ansible-demo-app.war"
        owner: tomcat
        group: tomcat
        mode: 0755

  handlers:
    - name: restart tomcat
      service: name=tomcat state=restarted
...  
