---
#Boxes
# For URLs: need to think another place! Maybe Hashicorp Vagrant repo
vbox:
  master:
    name: ansible_nix_master.box
    md5: 5a6d00cb940fd58316c8d5f8a41525df
    url: https://drive.google.com/uc?authuser=0&id=0B6Fexn49WvemQnpZcllaV2pVMjA&export=download
    folder: /opt/boxes/master
    ip: 192.168.33.101
    mem: 1024
  slave_nix:
    name: ansible_nix_slave.box
    md5: 135395388abd2fbdc080f81b4e9831a2
    url: https://drive.google.com/uc?authuser=0&id=0B6Fexn49WvemcXI2YUowOXZMdjA&export=download
    folder: /opt/boxes/nix_slave
    ip: 192.168.33.102
    mem: 1024
  slave_win:
    name: ansible_win_slave.box
    md5: a1c2a44eb551f904e7be3848175cb87b
    url: https://drive.google.com/uc?authuser=0&id=0B6Fexn49WvemY3BqeUxIQ3dHeVU&export=download
    folder: /opt/boxes/win_slave
    ip: 192.168.33.103
    mem: 2584
