- name: Add boxes
  block:
    - name: Exec vagrant box add
      win_command: "vagrant box add --checksum-type md5 --checksum {{ item.value['md5'] }} {{ item.value['box_name'] }}  {{ item.value['dest'] }}\\{{ item.value['box_name'] }}.box"
      with_dict: "{{ boxes }}"
      register: boxadd_out
      changed_when:
        - ("Successfully added box" in boxadd_out.stdout)
      failed_when:
        - not ("The box you\'re attempting to add already exists" in boxadd_out.stderr)
        - not ("Successfully added box" in boxadd_out.stdout)
    - debug:
        var: boxadd_out
        verbosity: 1
  when: boxes is defined
  tags: add_boxes
