- name: Configure boxes
  block:
    - name: Check Vagrantfile
      win_stat:
        path: "{{ item.value['dest'] }}\\Vagrantfile"
      with_dict: "{{ boxes }}"
      register: vagrantfile_out
#      failed_when:
#        - not (vagrantfile_out.stat.exist)
#        - vagrantfile_out.stat.isdir
    - name: Set ip address
      win_lineinfile:
        path:  "{{ item.value['dest'] }}\\Vagrantfile"
        regexp: 'config\.vm\.network'
        line: '  config.vm.network "private_network", ip: "{{ item.value["ip"] }}"'
      with_dict: "{{ boxes }}"
  when: boxes is defined
  tags: config_boxes
