- name: Vagrant destroy boxes
  block:
    - name: Kill all VBoxHeadless processes
      win_shell: Get-Process VBoxHeadless | Stop-Process -Confirm:$false
      register: kill_out
      failed_when:
        - not ("Cannot find a process with the name" in kill_out.stderr)
        - not ("Не удалось найти процесс с именем" in kill_out.stderr)
      ignore_errors: true

    - name: Clean user VirtualBox VMs
#      win_shell: Get-ChildItem -Recurse -Filter "{{ item.value['box_name'] }}*" | Remove-Item -Force -Recurse -Confirm:$false
      win_shell: Get-ChildItem -Recurse | Remove-Item -Force -Recurse -Confirm:$false
      args:
        chdir: C:\Users\DevOps\VirtualBox VMs\
      with_dict: "{{ boxes }}"

  when:
    - boxes is defined
    - destroy
  tags: destroy 
