- name: Vagrant destroy boxes
  block:
#    - name: Get vagrant global status
#      shell: vagrant global-status --prune
#      register: vagr_glob_stat

    - name: Kill all VBoxHeadless processes
      win_shell: Get-Process VBoxHeadless | Stop-Process -Confirm:$false
      register: kill_out
      failed_when:
        - not ("Cannot find a process with the name" in kill_out.stderr)
        - not ("Не удалось найти процесс с именем" in kill_out.stderr)
        - not ("NoProcessFoundForGivenName" in kill_out.stderr)
      ignore_errors: true

    - name: Clean .vagrant in dest
      win_shell: Get-ChildItem -Recurse | Remove-Item -Force -Exclude:'*.box' -Recurse -Confirm:$false
      args:
        chdir: "{{ item.value['dest'] }}"
      with_dict: "{{ boxes }}"

    - debug:
        msg: "Dest: {{ item.value['dest'] }}"
      with_dict: "{{ boxes }}"

    - name: Clean course user VirtualBox VMs
#      win_shell: Get-ChildItem -Recurse -Filter "{{ item.value['box_name'] }}*" | Remove-Item -Force -Recurse -Confirm:$false
      win_shell: Get-ChildItem -Recurse | Remove-Item -Force -Recurse -Confirm:$false
      args:
        chdir: C:\Users\DevOps\VirtualBox VMs\
      with_dict: "{{ boxes }}"

    - name: Clean user user VirtualBox VMs
      win_shell: Get-ChildItem -Recurse | Remove-Item -Force -Recurse -Confirm:$false
      args:
        chdir: C:\Users\user\VirtualBox VMs\
      with_dict: "{{ boxes }}"

  when:
    - boxes is defined
    - destroy
  tags: destroy 
