- name: Uninstall vagrant
  block:
    - name: Uninstall old vagrant
      win_package:
        product_id: "{{ vagrant_old.distrib.product_id }}"
        state: absent
    - name: Uninstall current vagrant
      win_package:
        product_id: "{{ vagrant.distrib.product_id }}"
        state: absent 
  tags: uninstall
  when: uninstall

- name: Install vagrant
  block:
    - name: "Create folder for downloads: {{ downloads }}"
      win_file:
        path: "{{ downloads }}"
        state: directory
    - name: Download vagrant distrib
      win_get_url:
        url: "{{ vagrant.distrib.url }}"
        dest: "{{ downloads }}"
        force: no
      register: downlout
    - name: Install vagrant
      win_package:
        path: "{{ downlout.dest }}"
        product_id: "{{ vagrant.distrib.product_id }}"
        arguments: "/quiet /norestart"
        state: present
 tags: install
