---
# tasks file for vagrant_win/
- import_tasks: "./install.yml"
- import_tasks: "./copy.yml"
- import_tasks: "./add.yml"
- import_tasks: "./init.yml"
- import_tasks: "./config.yml"
- import_tasks: "./up.yml"
- import_tasks: "./destroy.yml"
