---
# tasks file for vagrant_win/
- fail:
  when: ansible_distribution != "Майкрософт Windows 10 Pro"

- name: Install vagrant
  
  block:
    - name: Download vagrant box
      win_get_url:
        url: "{{ vagrant.distrib.url }}"
        dest: "{{ downloads }}"
      register: downlout 
    - name: Install virtualbox
      win_package:
        path: "{{ downlout.dest }}"
        product_id: "{{ vagrant.distrib.product_id }}"
        arguments: "/quiet /norestart"
        state: present
  tags: install
