---
# tasks file for vagrant_win/
- name: Install vagrant
  block:
    - name: "Create folder for downloads: {{ downloads }}"
      win_file:
        path: "{{ downloads }}"
        state: directory
    - name: Download vagrant distrib 
      win_get_url:
        url: "{{ vagrant.distrib.url }}"
        dest: "{{ downloads }}"
        force: no
      register: downlout 
    - name: Install vagrant
      win_package:
        path: "{{ downlout.dest }}"
        product_id: "{{ vagrant.distrib.product_id }}"
        arguments: "/quiet /norestart"
        state: present
  tags: install

- name: Copy boxes
  block:
    - debug:
        var: item.value['dest']
        verbosity: 1
      with_dict: "{{ boxes }}"

    - name: Create or check destination
      win_file: 
        path: "{{ item.value['dest'] }}"
        state: directory
      with_dict: "{{ boxes }}"

    - name: Copy box
      win_copy:
        src: "{{ item.value['src'] }}/{{ item.value['file'] }}"
        dest: "{{ item.value['dest'] }}\\{{ item.value['file'] }}"
        force: yes # the file will only be transferred if the content is different than destination.
      with_dict: "{{ boxes }}"

    - name: Check box existance and md5-summ
      win_stat:
        path: "{{ item.value['dest'] }}\\{{ item.value['file'] }}"
        get_md5: true
      with_dict: "{{ boxes }}"

  when: boxes is defined
  tags: copy_boxes

- name: Vagrant up boxes
  block:
    - debug:
        msg: up
  when: boxes is defined
  tags: up
