- name: Vagrant up boxes
  block:
    - name: Exec vagrant up
      win_command: "vagrant up --provider virtualbox"
      args:
        chdir: "{{ item.value['dest'] }}"
      with_dict: "{{ boxes }}"
  when:
    - boxes is defined
    - up
  tags: up
