---
# tasks file for virtualbox_win/

- name: Uninstall virtualbox
  block:
    - name: Uninstall virtualbox
      win_package:
        product_id: "{{ virtualbox.distrib.product_id }}"
        state: absent 
  tags: uninstall
  when: uninstall

- name: Install virtualbox
  block:
    - name: "Create folder for downloads: {{ downloads }}"
      win_file:
        path: "{{ downloads }}"
        state: directory
    - name: Download virtualbox
      win_get_url:
        url: "{{ virtualbox.distrib.url }}"
        dest: "{{ downloads }}"
        force: no
      register: downlout 
    - name: Install virtualbox
      win_package:
        path: "{{ downlout.dest }}"
        product_id: "{{ virtualbox.distrib.product_id }}"
        arguments: "--silent"
        state: present
  tags: install


