---
- name: Disable apt autoupdate
  template:
    src: 20auto-upgrades.j2
    dest: "/etc/apt/apt.conf.d/20auto-upgrades"
    owner: "root"
    group: "root"
- name: Update packages
  apt:
    upgrade: yes
    update_cache: yes
- name: Install Python Pip
  apt:
    name: python-pip
    state: latest
    update_cache: yes
- name: Install misc
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - aptitude
    - vim
    - tree
    - git
    - default-jdk
    - curl
  tags: install-packages
