---
- name: Update packages
  apt: 
    upgrade: yes
    update_cache: yes
- name: Install Python Pip
  apt:
    name: python-pip
    state: latest
    update_cache: yes
- name: Install misc
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - aptitude
    - vim
    - tree
    - git
