---
- name: Remove update-notifier
  apt:
    name: update-notifier
    state: absent

- name: Apt periodic
  template:
    src: 10periodic.j2
    dest: "/etc/apt/apt.conf.d/10periodic"
    owner: "root"
    group: "root"

- name: Apt autoupgrade
  template:
    src: 20auto-upgrades.j2
    dest: "/etc/apt/apt.conf.d/20auto-upgrades"
    owner: "root"
    group: "root"

- name: Update packages
  apt:
    upgrade: no 
    update_cache: yes

- name: Install Python Pip
  apt:
    name: python-pip
    state: latest
    update_cache: yes

- name: Install misc
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ packages }}"
  tags: install-packages

- name: Install Python modules
  pip: 
    name: "{{ item }}"
    state: present
  with_items: "{{ py_modules }}"
