---
#Docker repo
key_server: "hkp://p80.pool.sks-keyservers.net:80"
repo_server: "deb https://apt.dockerproject.org/repo ubuntu-xenial main"
repo_key: "58118E89F3A912897C070ADBF76221572C52609D"

#Docker images
image:
  juseppe: lanwen/juseppe
  bitbucket: atlassian/bitbucket-server:5.2
  jenkins: jenkins:2.60.2
  socat: bobrik/socat:latest
  nexus: sonatype/nexus3:3.5.0
  ldap: lavcraft/slapd:test
  sonar: sonarqube:6.4-alpine
  slave: lavcraft/jnlp-slave-dind
